spring.config.import=optional:file:.env[.properties],optional:file:.env.prod[.properties]

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:true}

# AWS
cloud.aws.region=${CLOUD_AWS_REGION:us-east-1}
cloud.aws.endpoint.s3=${CLOUD_AWS_ENDPOINT_S3:}
cloud.aws.endpoint.sqs=${CLOUD_AWS_ENDPOINT_SQS:}
cloud.aws.accessKey=${CLOUD_AWS_ACCESS_KEY:}
cloud.aws.secretKey=${CLOUD_AWS_SECRET_KEY:}

# Application infrastructure
application.s3.bucket=${APPLICATION_S3_BUCKET:}
application.sqs.queueUrl=${APPLICATION_SQS_QUEUE_URL:}
application.sqs.dlqUrl=${APPLICATION_SQS_DLQ_URL:}
application.sqs.maxRetries=${APPLICATION_SQS_MAX_RETRIES:5}
