# Local development schema generation
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}

# AWS
cloud.aws.region=${CLOUD_AWS_REGION:us-east-2}
cloud.aws.endpoint.s3=${CLOUD_AWS_ENDPOINT_S3:https://localhost.localstack.cloud:4566}
cloud.aws.endpoint.sqs=${CLOUD_AWS_ENDPOINT_SQS:https://localhost.localstack.cloud:4566}
cloud.aws.accessKey=${CLOUD_AWS_ACCESS_KEY:test}
cloud.aws.secretKey=${CLOUD_AWS_SECRET_KEY:test}

# Application infrastructure
application.s3.bucket=${APPLICATION_S3_BUCKET:upload}
application.sqs.queueUrl=${APPLICATION_SQS_QUEUE_URL:https://localhost.localstack.cloud:4566/000000000000/upload-queue}
